# Generated by Django 3.0.3 on 2020-02-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicusers', '0002_auto_20200220_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
