# Generated by Django 3.0.3 on 2020-02-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_genre', models.CharField(max_length=50)),
                ('artist_email', models.CharField(max_length=100)),
                ('artist_location', models.CharField(max_length=100)),
                ('artist_social', models.CharField(max_length=100)),
                ('artist_website', models.CharField(max_length=100)),
                ('artist_bio', models.TextField()),
            ],
        ),
    ]
