# Generated by Django 3.0.3 on 2020-02-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='detail_company',
            field=models.CharField(default='Enter Company Representative', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='detail_membership',
            field=models.CharField(default='Enter Membership Group', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='detail_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_email',
            field=models.CharField(default='Enter Email', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_genre',
            field=models.CharField(default='Enter Genre', max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_location',
            field=models.CharField(default='Where Are You Located', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(default='Enter Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_social',
            field=models.CharField(default='Enter Primary Social Network', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_website',
            field=models.CharField(default='Enter Personal Website', max_length=100),
        ),
    ]
