# Generated by Django 3.0.3 on 2020-02-19 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_company', models.CharField(default='Enter Company Representative', max_length=100)),
                ('detail_membership', models.CharField(default='Enter Membership Group', max_length=100)),
                ('detail_picture', models.ImageField(default='default.jpg', upload_to='artist/picture/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='musicsite.Artist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
