# Generated by Django 3.0.3 on 2020-02-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicsite', '0002_auto_20200219_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
