# Generated by Django 3.0.3 on 2020-02-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsite', '0003_delete_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_social',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_website',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='detail_company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='detail_membership',
            field=models.CharField(max_length=100),
        ),
    ]
